# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: shirinPC

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkUserInputPath: "/Library/Java/JavaVirtualMachines/jdk-18.0.2.jdk/Contents/Home"
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    options: 'test -PextentReport'
    goals: 'package'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/Users/shirin/myagent/_work/1/s/report'
    artifact: 'report'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()